export * from './slices/slices'
export { default as store } from './store/store'
export { default as adminSlice } from './slices/adminSlice/adminSlice'
export { default as userSlice } from './slices/userSlice/userSlice'
export { default as headerSlice } from './slices/headerSlice/headerSlice'
export { default as settingsSlice } from './slices/settingsSlice/settingsSlice'
